"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";

export default function NewEpisodePage() {
  const router = useRouter();
  const [saving, setSaving] = useState(false);
  const [uploadingArt, setUploadingArt] = useState(false);
  const [message, setMessage] = useState<{ type: "success" | "error"; text: string } | null>(null);

  const [form, setForm] = useState({
    captivateId: "",
    episodeNumber: "",
    guestName: "",
    guestEmail: "",
    riversideTitle: "",
    riversideKeywords: "",
    transcript: "",
    descriptionOriginal: "",
    publishDate: "",
    coverArtUrl: "",
    mp4Url: "",
  });

  async function handleCoverArtUpload(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    setUploadingArt(true);
    const fd = new FormData();
    fd.append("file", file);
    fd.append("folder", "episode-art");
    const res = await fetch("/nextjs-app/api/admin/upload", {
      method: "POST",
      body: fd,
    });
    const data = await res.json();
    if (res.ok) {
      setForm((f) => ({ ...f, coverArtUrl: data.url }));
    } else {
      setMessage({ type: "error", text: data.error ?? "Upload failed" });
    }
    setUploadingArt(false);
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setSaving(true);
    setMessage(null);
    const res = await fetch("/nextjs-app/api/admin/episodes/create", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(form),
    });
    const data = await res.json();
    if (res.ok && data.id) {
      router.push(`/admin/episodes/${data.id}`);
    } else {
      setMessage({ type: "error", text: data.error ?? "Failed to create episode" });
      setSaving(false);
    }
  }

  return (
    <div className="max-w-4xl">
      <div className="flex items-center gap-3 mb-6">
        <Link href="/admin/episodes" className="text-sm text-gray-500 hover:text-gray-900">
          ← Episodes
        </Link>
        <span className="text-gray-300">/</span>
        <span className="text-sm text-gray-900 font-medium">New episode</span>
      </div>

      <div className="bg-white rounded-xl border border-gray-200 p-6 mb-6">
        <h1 className="text-lg font-semibold text-gray-900 mb-1">Create new episode</h1>
        <p className="text-sm text-gray-500">
          Fill in the details from Riverside and Captivate. Claude will generate all content after you save.
        </p>
      </div>

      {message && (
        <div className={`mb-4 px-4 py-3 rounded-lg text-sm ${message.type === "success" ? "bg-green-50 text-green-700 border border-green-200" : "bg-red-50 text-red-700 border border-red-200"}`}>
          {message.text}
        </div>
      )}

      <form onSubmit={handleSubmit}>
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

          {/* Left — main content */}
          <div className="lg:col-span-2 space-y-6">

            {/* Riverside content */}
            <div className="bg-white rounded-xl border border-gray-200 p-6">
              <h2 className="text-sm font-semibold text-gray-900 mb-4">
                Riverside content
              </h2>
              <div className="space-y-4">
                <div>
                  <label className="block text-xs font-medium text-gray-500 mb-1">
                    Working title <span className="text-red-400">*</span>
                  </label>
                  <input
                    type="text"
                    value={form.riversideTitle}
                    onChange={(e) => setForm((f) => ({ ...f, riversideTitle: e.target.value }))}
                    className="input"
                    placeholder="Title as generated by Riverside"
                    required
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-500 mb-1">
                    Keywords (from Riverside)
                  </label>
                  <input
                    type="text"
                    value={form.riversideKeywords}
                    onChange={(e) => setForm((f) => ({ ...f, riversideKeywords: e.target.value }))}
                    className="input"
                    placeholder="Paste keywords from Riverside"
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-500 mb-1">
                    Transcript <span className="text-brand-gold font-medium">← Claude&apos;s primary input</span>
                  </label>
                  <textarea
                    value={form.transcript}
                    onChange={(e) => setForm((f) => ({ ...f, transcript: e.target.value }))}
                    rows={12}
                    className="input font-mono text-xs"
                    placeholder="Paste the full transcript from Riverside here — this is what Claude uses to generate all content"
                  />
                  {form.transcript && (
                    <p className="text-xs text-gray-400 mt-1">
                      {form.transcript.length.toLocaleString()} characters
                    </p>
                  )}
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-500 mb-1">
                    Show notes (from Riverside)
                  </label>
                  <textarea
                    value={form.descriptionOriginal}
                    onChange={(e) => setForm((f) => ({ ...f, descriptionOriginal: e.target.value }))}
                    rows={5}
                    className="input"
                    placeholder="Paste Riverside show notes (optional — used as backup if no transcript)"
                  />
                </div>
              </div>
            </div>

          </div>

          {/* Right — metadata and assets */}
          <div className="space-y-6">

            {/* Episode details */}
            <div className="bg-white rounded-xl border border-gray-200 p-6">
              <h2 className="text-sm font-semibold text-gray-900 mb-4">Episode details</h2>
              <div className="space-y-4">
                <div>
                  <label className="block text-xs font-medium text-gray-500 mb-1">Episode number</label>
                  <input
                    type="number"
                    value={form.episodeNumber}
                    onChange={(e) => setForm((f) => ({ ...f, episodeNumber: e.target.value }))}
                    className="input"
                    placeholder="e.g. 16"
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-500 mb-1">Guest name</label>
                  <input
                    type="text"
                    value={form.guestName}
                    onChange={(e) => setForm((f) => ({ ...f, guestName: e.target.value }))}
                    className="input"
                    placeholder="Full name"
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-500 mb-1">Guest email</label>
                  <input
                    type="email"
                    value={form.guestEmail}
                    onChange={(e) => setForm((f) => ({ ...f, guestEmail: e.target.value }))}
                    className="input"
                    placeholder="guest@example.com"
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-500 mb-1">Publish date</label>
                  <input
                    type="date"
                    value={form.publishDate}
                    onChange={(e) => setForm((f) => ({ ...f, publishDate: e.target.value }))}
                    className="input"
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-500 mb-1">
                    Captivate episode ID
                  </label>
                  <input
                    type="text"
                    value={form.captivateId}
                    onChange={(e) => setForm((f) => ({ ...f, captivateId: e.target.value }))}
                    className="input"
                    placeholder="Paste from Captivate draft"
                  />
                  <p className="text-xs text-gray-400 mt-1">
                    Create the draft in Captivate first, then paste the ID here
                  </p>
                </div>
              </div>
            </div>

            {/* Assets */}
            <div className="bg-white rounded-xl border border-gray-200 p-6">
              <h2 className="text-sm font-semibold text-gray-900 mb-4">Assets</h2>
              <div className="space-y-4">
                <div>
                  <label className="block text-xs font-medium text-gray-500 mb-1">
                    Cover art
                  </label>
                  {form.coverArtUrl ? (
                    <div>
                      <img
                        src={form.coverArtUrl}
                        alt="Cover art"
                        className="w-full rounded-lg border border-gray-200 mb-2"
                      />
                      <button
                        type="button"
                        onClick={() => setForm((f) => ({ ...f, coverArtUrl: "" }))}
                        className="text-xs text-red-500 hover:text-red-700"
                      >
                        Remove
                      </button>
                    </div>
                  ) : (
                    <div>
                      <label className="flex items-center justify-center w-full h-24 border-2 border-dashed border-gray-300 rounded-lg cursor-pointer hover:border-brand-purple transition-colors">
                        <div className="text-center">
                          <p className="text-xs font-medium text-gray-600">
                            {uploadingArt ? "Uploading..." : "Click to upload cover art"}
                          </p>
                          <p className="text-xs text-gray-400">JPG, PNG, WebP</p>
                        </div>
                        <input
                          type="file"
                          accept="image/jpeg,image/png,image/webp"
                          onChange={handleCoverArtUpload}
                          className="hidden"
                          disabled={uploadingArt}
                        />
                      </label>
                      <p className="text-xs text-gray-400 mt-1">
                        Upload after Canva artwork is ready
                      </p>
                    </div>
                  )}
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-500 mb-1">
                    MP4 URL (Google Drive)
                  </label>
                  <input
                    type="text"
                    value={form.mp4Url}
                    onChange={(e) => setForm((f) => ({ ...f, mp4Url: e.target.value }))}
                    className="input"
                    placeholder="Paste Google Drive MP4 link"
                  />
                  <p className="text-xs text-gray-400 mt-1">
                    Can be added later before publishing
                  </p>
                </div>
              </div>
            </div>

            {/* Save button */}
            <button
              type="submit"
              disabled={saving || !form.riversideTitle}
              className="w-full px-4 py-3 text-sm font-medium text-white bg-gray-900 rounded-lg hover:bg-gray-800 disabled:opacity-50 transition-colors"
            >
              {saving ? "Creating episode..." : "Create episode → Generate with Claude"}
            </button>
            <p className="text-xs text-gray-400 text-center">
              Claude will generate all content automatically after saving
            </p>
          </div>
        </div>
      </form>
    </div>
  );
}
