kind = "api"
previewPath = "/api-server"
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/api-server"]

[services.development]
run = "pnpm --filter @workspace/api-server run dev"
